### ISSUE TITLE
Milestone 1 To Do Summary

### ISSUE THREAD

**Issue by miyer26** [UBC-MDS/magmaviz#1]
GitHub Repo and project structure
License
Contributors( on README.md)
Conduct.md (code of conduct)
Contributing.md (with GitHub Flow)
README.md (summary, list of functions, overall fit in python verse)
Function documentation (1 from each member)
Need to work on our own branches for our individual functions

**Comment by miyer26** [comment]
Updated our kanban board to reflect the tasks!

**Comment by ruben1dlg** [comment]
Thanks for updating the board!

I am working now on the correlation plot function documentation and the CONTRIBUTING file
