### ISSUE TITLE
Update README.md

### ISSUE THREAD

**Issue by miyer26** [UBC-MDS/magmaviz#2]

**Comment by iamMoid** [comment]
I can take this up.

**Comment by iamMoid** [comment]
Can you pass on any work you have already done or if you have any thoughts/write-ups. I can build off of it. Thanks!

**Comment by miyer26** [comment]
Sure, here is what I have so far: 

EDA is one of the key steps in a machine learning project. This package aims to make this process easy by providing functions to plot four common types of plots with the magma theme. To maximize interpretability, the plots have defined color schemes (discrete, diverging, sequential) based on the kind of data they show.

This is for the high level summary.

**Comment by iamMoid** [comment]
ok great, this helps. Thanks! Do let me know if you have any info on how this ties back with the python verse.

**Comment by miyer26** [comment]
My thoughts on where this could fit into the greater python-verse are: 

Our package will build onto the existing features of Altair and serves as an automated plotter. It is a higher level implementation of it. Essentially it circumvents the need to code every single detail and allows the user to focus on the output.

**Comment by miyer26** [comment]
Thanks for taking this up Moid :)

**Comment by miyer26** [comment]
Here is the doctoring for my function for reference: 

"""Plot a boxplot with the magma color scheme and an option to facet.

    Parameters
    ----------
    df : dataframe
        Dataframe containing the variables for plotting
    x : string
        Column-name of the numerical variable to view the distribution of
    y : list
        Column names of the categorical variables to assign boxes to
    facet : boolean
        Determines whether seprate graphs will be created for each category

    Returns
    -------
    altair.vegalite.v4.api.Chart
        Boxplot displaying distribution of categorical variables with/without faceting

    Examples
    --------
    >>> from data_visualization.data_visualization import boxplot
    >>> plot_words(mtcars, horsepower, cars, facet=True)
    """

**Comment by miyer26** [comment]
Hey Moid, I have found some similar high level packages that are built on visualization libraries: 

- https://pypi.org/project/deneb/ (Altair) - uses the same base as this package
- https://github.com/ajaymaity/eda-viz (Matplotlib) 
- https://pypi.org/project/spartan-viz/ (Matplotlib) - same philosophy as this package: focus on good use of color

**Comment by ruben1dlg** [comment]
I also found this package for visualization:

-  https://github.com/mwaskom/seaborn (Matplotlib)

This one seems to be one of the most famous viz packages in the python world, and seems to be focused in making graphs both attractive and informative. I know this goes way beyond to what we are doing, but will it be a good idea to mention it? Or just Altair (since we are using it as base) and other high level packages like the ones mentioned by @miyer26 ?
