### ISSUE TITLE
Update test_corrplot.py conditions to check for numeric columns

### ISSUE THREAD

**Issue by iamMoid** [UBC-MDS/magmaviz#39]
`if df[col].dtype == 'float' or df[col].dtype == 'int':`

Can you update this to include:

`if df[col].dtype == 'float' or df[col].dtype == 'int' or df[col].dtype == 'float64' or df[col].dtype == 'int64':`

**Comment by ruben1dlg** [comment]
Of course! I was just working on it! 😀 Thanks!!
