### ISSUE TITLE
Create correlation plot function

### ISSUE THREAD

**Issue by miyer26** [UBC-MDS/magmaviz#5]

**Comment by ruben1dlg** [comment]
I'm working on the documentation for the python version of the function! 😀

**Comment by iamMoid** [comment]
Let's think of adding some auxiliary inputs as well to the function

**Comment by iamMoid** [comment]
For e.g. 'shape = "circle"' could be a non-mandatory input with default value as circle. This would plot filled circles as the correlation matrix. The user could switch to squares (heatmap style) by passing 'shape = "square"'
