### ISSUE TITLE
Create scatterplot function

### ISSUE THREAD

**Issue by miyer26** [UBC-MDS/magmaviz#6]

**Comment by iamMoid** [comment]
Thanks, will create a branch to work on the scatterplot function.

**Comment by iamMoid** [comment]
I am drafting the docstring for the scatterplot.py function and was deciding on the input variables. Three mandatory inputs would be the dataframe, x-axis, y-axis inputs. What if the user wants to add a categorical column as "color" to the chart? I can create an auxiliary variable with default value blank, like: c = "". The function itself will require two different plots based on the condition to check whether c is blank or a variable has been assigned.

**Comment by iamMoid** [comment]
@miyer26 PR with the scatterplot.py function is ready for you to review
